### ISSUE TITLE
Fetching recent headers

### ISSUE THREAD

**Issue by t-bast** [TheBlueMatt/headersdns#2]
Hey!

This was easy enough to integrate into [eclair](https://github.com/acinq/eclair), but I'm having issues fetching recent blocks.
It looks like bitcoinheaders.net is ~100 blocks late (not getting any result for recent blocks).
Is that expected?

Thanks!

**Comment by TheBlueMatt** [comment]
Oof. Should be fixed in a few minutes on the next update, but more reason to have more sources than just mine :).

**Comment by TheBlueMatt** [comment]
Looks like its fixed now.

**Comment by t-bast** [comment]
Great, it works indeed, thanks!
Don't worry I'm adding multiple other sources, and that will allow me to notify you when headersdns is behind :smile:
